spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.20.20.104:3306/zhubajie_bj_declareopen
    username: writer
    password: zhubajie
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 8 #初始化连接大小
      min-idle: 5 #最小空闲连接数
      max-active: 10 #最大连接数
      query-timeout: 6000 #查询超时时间
      transaction-query-timeout: 6000 #事务查询超时时间
      remove-abandoned-timeout: 1800 #关闭空闲连接超时时间
      filter-class-names: stat
      filters: stat,config
  mybatis:
    # 配置xml 的扫描路径
    mapper-locations: classpath*:mapper/*.xml
    check-config-location: true
    type-aliases-package: org.spring.boot.po